package com.example.guardsprotectionapp.models
import com.squareup.moshi.Json


data class UserModel(
    @Json(name = "address")
    val address: String?,
    @Json(name = "addressCity")
    val addressCity: String?,
    @Json(name = "addressHouseNumber")
    val addressHouseNumber: String?,
    @Json(name = "addressPostalCode")
    val addressPostalCode: String?,
    @Json(name = "alarm")
    val alarm: Boolean?,
    @Json(name = "assignedOffers")
    val assignedOffers: Long?,
    @Json(name = "auto")
    val auto: Boolean?,
    @Json(name = "birthdate")
    val birthdate: String?,
    @Json(name = "birthdateDisplay")
    val birthdateDisplay: String?,
    @Json(name = "birthplace")
    val birthplace: String?,
    @Json(name = "bl")
    val bl: Boolean?,
    @Json(name = "bsw")
    val bsw: Boolean?,
    @Json(name = "createdBy")
    val createdBy: Int?,
    @Json(name = "createdDate")
    val createdDate: String?,
    @Json(name = "eh")
    val eh: Boolean?,
    @Json(name = "email")
    val email: String?,
    @Json(name = "ex")
    val ex: Boolean?,
    @Json(name = "firebaseMobileAppToken")
    var firebaseMobileAppToken: String?,
    @Json(name = "fs")
    val fs: Boolean?,
    @Json(name = "fullName")
    val fullName: String?,
    @Json(name = "groups")
    val groups: List<Int?>?,
    @Json(name = "hiredTo")
    val hiredTo: String?,
    @Json(name = "hiredToAe")
    val hiredToAe: String?,
    @Json(name = "hiredToEh")
    val hiredToEh: String?,
    @Json(name = "hund")
    val hund: Boolean?,
    @Json(name = "id")
    val id: Int?,
    @Json(name = "modifiedBy")
    val modifiedBy: Int?,
    @Json(name = "modifiedDate")
    val modifiedDate: String?,
    @Json(name = "name")
    val name: String?,
    @Json(name = "nationality")
    val nationality: String?,
    @Json(name = "oldPassword")
    val oldPassword: String?,
    @Json(name = "optik")
    val optik: Boolean?,
    @Json(name = "password")
    val password: String?,
    @Json(name = "phone")
    val phone: String?,
    @Json(name = "picture")
    val picture: Picture?,
    @Json(name = "qso")
    val qso: Boolean?,
    @Json(name = "role")
    val role: String?,
    @Json(name = "surname")
    val surname: String?,
    @Json(name = "svnr")
    val svnr: Long?,
    @Json(name = "vrk")
    val vrk: Boolean?,
    @Json(name = "wp")
    val wp: Boolean?,
    @Json(name = "zu")
    val zu: Boolean?
)

data class Picture(
    @Json(name = "createdBy")
    val createdBy: Long?,
    @Json(name = "createdDate")
    val createdDate: String?,
    @Json(name = "fileData")
    val fileData: String?,
    @Json(name = "fileExtension")
    val fileExtension: String?,
    @Json(name = "fileName")
    val fileName: String?,
    @Json(name = "id")
    val id: Long?,
    @Json(name = "isDeleted")
    val isDeleted: Boolean?,
    @Json(name = "modifiedBy")
    val modifiedBy: Long?,
    @Json(name = "modifiedDate")
    val modifiedDate: String?
)